-- A kliens belépési pontja.

local Hud = require(script.Parent.Hud)
local Effects = require(script.Parent.Effects)
local BlobAnimator = require(script.Parent.BlobAnimator)
local Sounds = require(script.Parent.Sounds)
local Trails = require(script.Parent.Trails)
local MapView = require(script.Parent.MapView)
local Pvp = require(script.Parent.Pvp)

Hud.start()
Effects.start()
BlobAnimator.start()
Sounds.start()
Trails.start()
MapView.start()
Pvp.start()
